services:
  ece566:
    build:
      context: .
      dockerfile: Dockerfile.remote
    cap_add:
      - SYS_PTRACE
    security_opt: # options needed for debugging
      - seccomp:unconfined
      - apparmor:unconfined
    privileged: true
    volumes:
      - .:/ece566
    container_name: ece566
    ports:
       - "2222:22"
